version: '3'
services: 
  mysql:
    image: 'mysql'
    ports: 
      - '3307:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: dicky
      MYSQL_DATABASE: db_dot_rajaongkir
      MYSQL_USER: dicky
      MYSQL_PASSWORD: dicky123
    networks: 
      - 'database-net'
    volumes: 
      - ./data:/var/lib/mysql
  
  adminer:
    image: 'adminer'
    ports: 
      - '8081:8080'
    networks: 
      - 'database-net'
networks:
  database-net: